In [16]:
import numpy as np
import pandas as pd

In [2]:
# create an array of zeros and length 10 with np.zeros(size)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# create an array of ones and length 10 with np.ones(size)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# create an array of length 10 filled with 2.5 np.full(length, value)
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
# convert a python list to an array with
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [6]:
# arrays can be substituted with basically they are mutable e.g
arr[3] = 22
arr

array([ 1,  2,  3, 22,  5])

In [7]:
# create a range of numbers
# np.arange(initial, last_number - 1) 
# so range of 10 is 0 to 10-1 = 9
print(np.arange(10))
print(np.arange(3, 10))
# it doest return the last number defined.


[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


In [8]:
# takes a number takes the first two arguments as range value,
# the last argument as the length. numpy will split up the range in 
# such a way that the length of array returned is equal to the final argument
# and the values will be between the range(first two argument including the two args.)
print(np.linspace(0,1,25))
print(" -------------------------  ")
print(np.linspace(0, 100, 11))

[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]
 -------------------------  
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [9]:
# create nested arrays with
#       rows, columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# create an array from a python nested list
py_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

n = np.array(py_list)

In [11]:
# select rows
print(n[0])
# select on the second columns
print(n[:,1])
# change an element of an array
n[0, 1] = 50
# change a column of an array
n[:, 1] = [40, 50, 70]
print(" ================ ")
print(n)

[1 2 3]
[2 5 8]
[[ 1 40  3]
 [ 4 50  6]
 [ 7 70  9]]


In [12]:
# generate a random array.
# ............(row, column)
np.random.rand(5, 2)

array([[0.09495089, 0.98656208],
       [0.77959067, 0.70529513],
       [0.01816572, 0.51710838],
       [0.62815897, 0.9860926 ],
       [0.66749638, 0.40071334]])

In [14]:
# generate a random array of a normal distribution
# ............(row, column)
randn = np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
# To get same number random state we have to set random state to a number.
np.random.seed(2)
